
bin/func: 1_func.cpp
	g++ $< -o $@ -std=c++14 -pthread

bin/mem_func: 2_mem_func.cpp
	g++ $< -o $@ -std=c++11 -pthread

bin/in_array: 3_in_array.cpp
	g++ $< -o $@ -std=c++11 -pthread

bin/ref: 4_ref.cpp
	g++ $< -o $@ -std=c++11 -pthread
